# Generated by Django 5.1.6 on 2025-02-28 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('patient_id', models.CharField(max_length=50, unique=True)),
                ('current_location', models.CharField(max_length=200)),
                ('rescued_location', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('Safe', 'Safe'), ('Injured', 'Injured'), ('Critical', 'Critical'), ('Deceased', 'Deceased')], max_length=10)),
            ],
        ),
    ]
